<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Untitled Web Page</title>
<meta name="generator" content="Antenna 3.0">
<meta http-equiv="imagetoolbar" content="no">
<link rel="stylesheet" type="text/css" href="antenna.css" id="css">
<style type="text/css">.abs {position:absolute}</style>
<script type="text/javascript" src="antenna/auto.js"></script>
</head>
<body class="global">
<div id="lays394nbwem">
<div id="pict017ujyfm" class="hid abs" style="left:0px; top:50px; width:505px; height:610px;">
<img id="pict017ujyfmi" class="fil smf" src="coil_calc.jpg" alt="">
</div>
</div>
</body></html>
